version: 2.1

references:
  - &CERT_KEY certs-cache-{{ checksum "certs_cache_key" }}-v3

# Enable dynamic configuration
setup: true

filters: &all_tags
  tags:
    only: /^\d+\.\d+\.\d+([a-z0-9\-\+])*/

# Include the continuation orb for dynamic configuration
orbs:
  continuation: circleci/continuation@0.2.0

# Define jobs
jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - maybe_build_certs
      - run:
          name: Generate config
          command: |
            tools/circle-generate-config.sh generated_config.yml
      - continuation/continue:
          configuration_path: generated_config.yml # Use dynamically generated config

  build:
    docker:
      - image: cimg/base:current  # Use CircleCI's base image for container runners
    steps:
      - run:
          name: Say Hello
          command: echo "Hello, World! I'm running on a self-hosted runner!"
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/art-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/art-2;
      - store_artifacts:
          path: /tmp/art-1
          destination: artifact-file
      - store_artifacts:
          path: /tmp/artifacts

commands:
  maybe_build_certs:
    steps:
      - run:
          name: Prepare cache key
          command: tools/make-certs-cache-key.sh > certs_cache_key && cat certs_cache_key
      - restore_cache:
          name: Restore certificates
          key: *CERT_KEY
      - run:
          name: Build certificates if not cached
          command: test -f tools/ssl/mongooseim/key.pem || make certs
      - run:
          name: Print cert hashes for debugging
          command: find tools/ssl -type f -exec md5sum {} \; | sort
      - run:
          name: Continue if certificate exists
          command: test -f tools/ssl/mongooseim/key.pem
      - save_cache:
          name: Cache built certs
          key: *CERT_KEY
          paths:
            - ~/project/tools/ssl/ca
            - ~/project/tools/ssl/ca-clients
            - ~/project/tools/ssl/mongooseim

# Define workflows
workflows:
  setup:
    jobs:
      - setup:
          filters: *all_tags
  build-workflow:
    jobs:
      - build

